#!/bin/bash
th run.lua --dataset bn --year 2009 --datapath ../../../gitExclude/patches/pdNet/xBalinese/128x256 --cachepath ../../../gitExclude/resources/pdNet/Balinese/128x256/cache/encoder --model models/encoder.lua --save ../../../gitExclude/resources/pdNet/Balinese/128x256/trained/encoder --imHeight 128 --imWidth 256 --labelHeight 16 --labelWidth 32 --batchSize 30 --maxepoch 20 --ptModel ../../../gitExclude/resources/pdNet/Dibco/128x256/trained/encoder/model-2009.net
th run.lua --dataset bn --year 2009 --datapath ../../../gitExclude/patches/pdNet/xBalinese/128x256 --cachepath ../../../gitExclude/resources/pdNet/Balinese/128x256/cache/decoder --model models/decoder.lua --save ../../../gitExclude/resources/pdNet/Balinese/128x256/trained/decoder --imHeight 128 --imWidth 256 --labelHeight 128 --labelWidth 256 --batchSize 30 --maxepoch 20 --CNNModel ../../../gitExclude/resources/pdNet/Balinese/128x256/trained/encoder --ptModel ../../../gitExclude/resources/pdNet/Dibco/128x256/trained/decoder/model-2009.net
th run.lua --dataset bn --year 2009 --datapath ../../../gitExclude/patches/pdNet/xBalinese/128x256 --cachepath ../../../gitExclude/resources/pdNet/Balinese/128x256/cache/decoder --model models/pdNet.lua --save ../../../gitExclude/resources/pdNet/Balinese/128x256/trained/pdNet --imHeight 128 --imWidth 256 --labelHeight 128 --labelWidth 256 --batchSize 20 --CNNModel ../../../gitExclude/resources/pdNet/Balinese/128x256/trained/decoder --maxepoch 20	
cd ../visualize
th demo_PDdibco.lua -i ../../../gitExclude/patches/pdNet/xBalinese/128x256/test -d ../../../gitExclude/resources/pdNet/Balinese/128x256/trained/ -m pdNet --year 2009 --dataset bn -o ../../../gitExclude/patches/pdNet/xBalinese/xOutput_pdnet_128x256 --devID 2
cd ../utils
python dibcoImgJoin.py -i ../../../gitExclude/patches/pdNet/xBalinese/xOutput_pdnet_128x256 -o ../../../gitExclude/patches/pdNet/xBalinese/jOutput_pdnet_128x256 -c ../../../gitExclude/imgDataSets/balinese/pngs/test/img

